### ISSUE TITLE
Add a photo lightbox / gallery to see larger version of images

### ISSUE THREAD

**Issue by hamoid** [prachtsaal/prachtsaal.berlin#22]
I've searched a lot and there are trillions of photo gallery and lightbox JavaScript classes. I find it hard to choose one as every year there's a new framework and new libraries.

But maybe we can use this one which uses TailwindCSS?

https://github.com/CaesarDev/caesar-lightbox

Positive: small. Keyboard navigation works (arrows, ESC).
Negative: uses alpine.js (dependencies are not great). Doesn't seem to be zoomable on a phone. Doesn't use separate images for the thumbnail and the large version as other's do (which reduces data transfer when you don't browse all the large versions).

A demo: https://caesardev.se/docs/caesar-lightbox/

**Comment by mingness** [comment]
At least alpine.js is lightweight. This sounds like a great option to me.
