### ISSUE TITLE
Add newsletter subscription form

### ISSUE THREAD

**Issue by hamoid** [prachtsaal/prachtsaal.berlin#23]
There seems to be a `_includes/newsletter.html` but it's not yet used.

**Comment by mingness** [comment]
Yes, this is from the previous website, so it's inherited. I did not use it, to simplify, and because we don't seem to have a newsletter strategy yet? But we could implement something for sure.

**Comment by hamoid** [comment]
So I can recommend buttondown for the newsletter. It's what I've been using this year and I find it very pleasant.

If no one is against it we can add a link to https://buttondown.email/prachtsaal.berlin to let people subscribe. I'll ask in Telegram if people agree to use it and if so share the password.

**Comment by mingness** [comment]
This sounds good to me.
