### ISSUE TITLE
missing members pages

### ISSUE THREAD

**Issue by mingness** [prachtsaal/prachtsaal.berlin#30]
We are missing members pages on the website. solicit information and update.

**Comment by mingness** [comment]
Dominic is online. We are missing information from Chloe, Michelle, So, Gabor, Marta, Roberta, Stephan, Julia, Kazik.
We should remove Valerio.

Should we add an alumni section?

**Comment by mingness** [comment]
Good idea

**Comment by mingness** [comment]
Have just sent an email from the prachtsaal email account to currently outstanding members who are not on the website.

**Comment by hamoid** [comment]
I'll split this into separate issues so they can be closed independently :)
