### ISSUE TITLE
fix PR preview to work with jekyll

### ISSUE THREAD

**Issue by mingness** [prachtsaal/prachtsaal.berlin#56]
we currently are using

https://github.com/rossjrw/pr-preview-action

to preview PRs,

This puts the PR preview as a route
https://[owner].github.io/[repo]/pr-preview/pr-[number]/

This is currently not working with jekyll build, as the build still has all assets and navigation links going to the main site, without extra route for the subdirectory. using `baseurl` should allow the setting of a route, but this is somehow not sufficient.

**Comment by hamoid** [comment]
I asked at https://github.com/rossjrw/pr-preview-action/discussions/89

**Comment by mingness** [comment]
I think I know what needs to happen - I think we need to add {{ site.baseurl }} in front of every image and navigation link

**Comment by hamoid** [comment]
I suspected that might be the case. Easy to test. I need to add a new image with such a URL and see if the preview shows it.

**Comment by mingness** [comment]
Ah, are you about to work on it? I already created a branch linked to this issue. I can also work on the issue.

**Comment by mingness** [comment]
why don't you test, but I'll work on this issue?

**Comment by hamoid** [comment]
Ok, I do a quick test

**Comment by hamoid** [comment]
Works: https://prachtsaal.berlin/pr-preview/pr-58/

**Comment by hamoid** [comment]
Then this should be done for every URL: every `img src`, `link href`, `script src`, `a href`, `source src`, ...

**Comment by mingness** [comment]
rather than use that, I think relative_url filter is what we should do.
https://talk.jekyllrb.com/t/relative-url-and-baseurl/2051/6
